import Header from "./Layouts/Header";
import "./globals.css";
import { cookies } from "next/headers";
import Image from "next/image";
import Link from "next/link";
import Footer from "./Layouts/Footer";
import { Providers } from "./redux/providers";

export const metadata = {
  title: "riksham",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies();
  const value = cookieStore.get(process.env.COOKIE_TOKEN_NAME)?.value;

  let userData = {};
  if (value) {
    async function dataFetch(protocol_and_host) {
      const req = await fetch(
        `${protocol_and_host}/api/admin/user/data/${value}
        `,
        { cache: "no-cache" }
        // { next: { revalidate: 21600 } }
      );

      const { success, message, data } = await req.json();

      if (success) {
        data.token = value;
        userData = data;
      }
    }
    try {
      await dataFetch(process.env.PROTOCOL_AND_HOST);
    } catch (err) {
      await dataFetch(process.env.Second_Host_Name);
    }
  }
  const connectIn = value ? "login" : "sign-up";

  return (
    <html lang="en">
      <body>
        <Providers>
          <Header
            Link={Link}
            Image={Image}
            connect={connectIn}
            userData={userData}
          />
          {children}
          <Footer Link={Link} Image={Image} />
        </Providers>
      </body>
    </html>
  );
}
