import Header from "./Layouts/Header";
import "./globals.css";
import { cookies } from "next/headers";
import Image from "next/image";
import Link from "next/link";
import Footer from "./Layouts/Footer";

export const metadata = {
  title: "riksham",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookie = cookies().get("userInfo")?.value;
  const userInfo = cookie ? JSON.parse(cookie) : cookie;
  return (
    <html lang="en">
      <body>
        <Header Link={Link} Image={Image} userInfo={userInfo} />
        {children}
        <Footer Link={Link} Image={Image} />
      </body>
    </html>
  );
}
